name: Mirroring

on: [push, delete]

jobs:
  to_github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:EpitechPromo2026/B-DOP-200-MPL-2-1-bschocolatine-olivier.reynaud.git
          ssh_private_key:
            ${{ secrets.MY_SSH }}
